### ISSUE TITLE
Add: Site Footer

### ISSUE THREAD

**Issue by Iseluin** [ReCoded-Org/capstone-turkey-react-bursapediary#4]
Is your Feature Request Related to a Problem/a Blocker? Please Describe.
N/A

--------

Describe How the Solution Should Behave
The footer component should be displayed on all pages of the website, the component will be in the components directory in the src directory and imported into the app.js. All the links in the footer should reflect real pages on the website.

---------

Screenshots of the Design/if Any

---------

Additional context
Formik for input validation.
react-router-dom is already imported to the repo.
All routes should be a constant variable stored in the src/routes.js file and exported from there for ease of use.

**Comment by bayogluteoman** [comment]
There is no input in our last design of footer so I did not use Formik for input validation. Also I used svg for social media icons because we did not decide any library for icons. Maybe we can use Font Awesome Icons.
Screenshots of footer : 

-  
![image](https://user-images.githubusercontent.com/44370085/161526852-e171de89-20ac-45b2-aa65-68ead15ebf49.png)


<br/>

- 
![image](https://user-images.githubusercontent.com/44370085/161526125-629149d0-29dc-4fc1-869c-4a9c3b0fca70.png)

<br/>

-
 ![image](https://user-images.githubusercontent.com/44370085/161526365-90fa64d8-2964-4660-a6dc-c8afd056810d.png)
